name: Production Workflow

on:
  workflow_dispatch:

jobs:
  Deploy-Prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Production
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fiubify-middleware-production"
          heroku_email: "services.manager.web@gmail.com"
          usedocker: true
          appdir: ./app
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: PROD

