name: Staging Workflow

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm install --only=dev
        working-directory: ./app
      
      - name: Run linter
        run: npx eslint .
        working-directory: ./app

      - name: Run Tests
        run: npm test
        working-directory: ./app

  Deploy-Staging:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Staging
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fiubify-middleware-staging"
          heroku_email: "services.manager.web@gmail.com"
          usedocker: true
          appdir: ./app
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: STAGING

